### ISSUE TITLE
CA Review: Confusing wording could be clarified

### ISSUE THREAD

**Issue by sorainsm** [peter-michalski/LatticeBoltzmannSolvers#10]
The wording of which computational models you will use in Section 3.2 Scope of the Family is difficult to parse.

When reading it for the first time I was anticipating the total number of available computational models based on the "up to". 

I suggest replacing this with: "...will use 1D, 2D, and 3D computational models," or even stating "various computational models" and then showing the 1D, 2D, and 3D models as instance models, or just data definitions if you're looking to just use them.

![image](https://user-images.githubusercontent.com/11723492/66536103-dbf42180-eae9-11e9-9452-e7dea8e9e3c0.png)

**Comment by sorainsm** [comment]
Similarly I think "memory" here is confusing - as it seems like these are loaded into RAM and read from specific locations.

I'd suggest cutting out the "from memory" part and leaving it as "the system shall import the relevant coefficient weights.."

![image](https://user-images.githubusercontent.com/11723492/66539687-e832ab80-eaf6-11e9-9478-a5f0c1f17aae.png)

**Comment by peter-michalski** [comment]
I agree. The changes are reflected in e291ad6296946a877c21844db772b6e33ebb0dd3
