### ISSUE TITLE
CA Review: User referenced in Intended Reader section.

### ISSUE THREAD

**Issue by sorainsm** [peter-michalski/LatticeBoltzmannSolvers#11]
@peter-michalski this is likely just a typo or similar error, but Section 3.3 references the user at the end, not the intended reader. This will be confusing as there is a specific User Characteristics section later.

![image](https://user-images.githubusercontent.com/11723492/66536445-fda1d880-eaea-11e9-866a-fc3176adf1d5.png)

**Comment by peter-michalski** [comment]
Good catch. Updated in e291ad6296946a877c21844db772b6e33ebb0dd3
