### ISSUE TITLE
Question (CA): Intended Reader Characteristics

### ISSUE THREAD

**Issue by sorainsm** [peter-michalski/LatticeBoltzmannSolvers#12]
The Intended Reader Characteristics states that the user (intended reader) should have an undergraduate Level 1 understanding of physics.

Would it be more appropriate to specify this further to having taken an introductory fluid dynamics course?

I ask because my undergraduate physics knowledge from Eng 1 at McMaster didn't cover fluid dynamics in any way.

**Comment by peter-michalski** [comment]
This is a good point. The changes are in e291ad6296946a877c21844db772b6e33ebb0dd3
