### ISSUE TITLE
Suggestion (CA): Remove Potential System Constraints

### ISSUE THREAD

**Issue by sorainsm** [peter-michalski/LatticeBoltzmannSolvers#13]
@peter-michalski I think the potential system constraints you've listed are almost too abstract/generic. 

As I'm reading top-down I don't know the problem enough to see whether these really are constraints on the system, or just generic constraints of programming. My understanding was that we assume the hardware/operating system context is basically a perfect computer with infinite memory and features like concurrency or whatever was needed for the problem, and that system constraints were design decisions imposed on a perfect computer. For example, if the solution _must_ be written in a specific language, or _must_ use some other library to handle something, or images _have_ to be of a specific file type to be parsed correctly. If I've understood it correctly I don't think you have any system constraints.

@smiths if you could please clarify this (for at least my own understanding of system constraints) I'd appreciate it!

![image](https://user-images.githubusercontent.com/11723492/66536932-b6b4e280-eaec-11e9-994f-f382633dbff0.png)

**Comment by smiths** [comment]
@sorainsm, yes I agree.  @peter-michalski, you do not have any system constraints at this point.  In the implementation the computational power of the hardware will be very important, but there isn't anything that forces a specific hardware platform at this time.  Some will be better suited for the task at hand than others, but those are design decisions that will be made to achieve the best performance.

**Comment by peter-michalski** [comment]
I have removed this section in b226ef4a57b226248a37488e56b390c63140dcc8
