### ISSUE TITLE
Suggestion (CA): Add Terminology

### ISSUE THREAD

**Issue by sorainsm** [peter-michalski/LatticeBoltzmannSolvers#14]
As a layman with fluid dynamics, I think there are quite a few terms where including explicit definitions would benefit the reader (as currently stated with Undergraduate Level 1 Physics knowledge).

I will catalogue them here as I find them along with their first occurrence:

| Word | Pg. Number|
|-------:|-------------:|
| Lattice| 2|
| Links| 5|

**Comment by sorainsm** [comment]
Alternatively, changing the Intended Reader Characteristics to specify needing introduction to fluid dynamics or something equivalent would negate this, as they would be familiar with these terms in this context.

**Comment by peter-michalski** [comment]
The reader characteristics have been updated in 5ba7ec741ad70d9c0ee78cb807fb035077417b20
