### ISSUE TITLE
CA Review: Theoretical Models Are Incorporating Ref. By Information into the Description.

### ISSUE THREAD

**Issue by sorainsm** [peter-michalski/LatticeBoltzmannSolvers#15]
I think there's some mixing of the TM as a variability in here with the description.

From my understanding, the Description section is just to _explain_ the TM (what is it doing, what the symbols represent, when is it used). 

I suggest moving the information in the highlighted sentence to the Ref. By section for the TM.

![image](https://user-images.githubusercontent.com/11723492/66538065-d5b57380-eaf0-11e9-9157-968266ffd468.png)

This same issue applies to all TM.

**Comment by peter-michalski** [comment]
I agree. The change was made in e291ad6296946a877c21844db772b6e33ebb0dd3
