### ISSUE TITLE
Question (CA): Should Theoretical Model 2 Be A Data Definition?

### ISSUE THREAD

**Issue by sorainsm** [peter-michalski/LatticeBoltzmannSolvers#16]
@peter-michalski by nature of it being called an operator, I think that TM2 should actually be a DD.

@smiths can I get your opinion on this? I don't know enough about fluid dynamics to know if this is in the right section.

![image](https://user-images.githubusercontent.com/11723492/66538299-cbe04000-eaf1-11e9-8760-6960c7e697cd.png)

**Comment by smiths** [comment]
Whether or not T2 is actually a DD depends on how it is used.  If a theoretical model is not refined into something else, if it is just referenced, but not refined, it can be a DD.  As currently used in the documentation, T2 is not refined, and could become a DD.  However, @peter-michalski will have to decide if he actually should fix this by refining T2.  The text of the description suggests that the equation can be developed into further specific instances.  In that case, it should remain a theoretical model, but the instances should be given.

@peter-michalski, I think what you are really after here is to present the version of the Boltzmann Transport Equation with collisions (as discussed in the scanned pages attached to #21).  The function omega is than a variability.  This specific value of omega, Bhatnagar-Gross-Krook, is one value of the variability.  If this is the case, then this should be a DD.

**Comment by peter-michalski** [comment]
Changed to a DD in b226ef4a57b226248a37488e56b390c63140dcc8
