### ISSUE TITLE
CA Review: Grammatical Errors and Simplifying Writing

### ISSUE THREAD

**Issue by sorainsm** [peter-michalski/LatticeBoltzmannSolvers#17]
@peter-michalski A2 should be simplified by replacing highlighted section with **fluid may flow**.

![image](https://user-images.githubusercontent.com/11723492/66538491-94be5e80-eaf2-11e9-898f-24f24026dc5a.png)

**Comment by sorainsm** [comment]
@peter-michalski A7's highlighted section should be "Its" for possessive its.

![image](https://user-images.githubusercontent.com/11723492/66538587-0eeee300-eaf3-11e9-8726-f5f28b9a570e.png)

**Comment by sorainsm** [comment]
Remove the specific details of this especially if you want it to be a run-time decision.

I suggest instead: "R7: The system shall output the results of the calculations in a manner consistent with the decisions made regarding output variabilities."

This would then encapsulate your idea of encoding too which is otherwise not mentioned in this output statement.

![image](https://user-images.githubusercontent.com/11723492/66539750-3d6ebd00-eaf7-11e9-9d94-3928a26cf0ba.png)

**Comment by sorainsm** [comment]
Similarly I think "memory" here is confusing - as it seems like these are loaded into RAM and read from specific locations.

I'd suggest cutting out the "from memory" part and leaving it as "the system shall import the relevant coefficient weights.."

![image](https://user-images.githubusercontent.com/11723492/66539831-92123800-eaf7-11e9-9c66-0825a71474d4.png)

The same for R6 - remove references to memory.

![image](https://user-images.githubusercontent.com/11723492/66539852-a48c7180-eaf7-11e9-8b36-faee3328bb70.png)

**Comment by peter-michalski** [comment]
updated in e291ad6296946a877c21844db772b6e33ebb0dd3
