### ISSUE TITLE
CA Review: Binding Times of Input and Output Variabilities Need to be Tweaked

### ISSUE THREAD

**Issue by sorainsm** [peter-michalski/LatticeBoltzmannSolvers#18]
@peter-michalski I think that the binding times of your input variabilities could use tweaking.

From my understanding of reading your document, many of the things you have listed as "scope time" bindings should really be compile time or run time bindings. The velocity, time, position vector, and others all seem like they are inputs a user would feed to the system in order for it solver to produce a model. By listing them as scope time variables you're saying that you have made a decision that your family of solvers only deals with problems that have one specific set of velocities bound at scope time (e.g. Set R : e > 0). From what's written here it seems like you would like for some of these things to be freely passed in by the end user.

I have highlighted in pink which variabilities I think would be better suited to run-time binding.
Yellow highlights indicate what I think would be compile time bindings.

![image](https://user-images.githubusercontent.com/11723492/66538834-0cd95400-eaf4-11e9-8c88-31e17b5bb3d0.png)

**Comment by sorainsm** [comment]
Associated: I think you can remove fluid parameters (highlighted in yellow) from your input variabilities as the _actual_ inputs (velocity, time, etc) are listed below it.

![image](https://user-images.githubusercontent.com/11723492/66539090-ecf66000-eaf4-11e9-9d8a-1b3ec9bf50a1.png)

**Comment by sorainsm** [comment]
Similarly I think that the binding times of your outputs should be changed to compile time. From my understanding labeling something as a run-time binding means that the decision about it will only be made at run time. For example, the "destination for output" variability being run time means the user needs to specify to the program as input the option of either file, screen, or memory.

I think that some of these are appropriate to be run time decisions (e.g. fluid characteristics), but that things like the encoding of the output, or the graphical model should be selected by you at compile time so as to refine the scope of your family better.

![image](https://user-images.githubusercontent.com/11723492/66539365-a2c1ae80-eaf5-11e9-8828-86ef3e258e3d.png)

**Comment by peter-michalski** [comment]
Thank you for pointing this out and explaining it. After reviewing these tables and my understanding of binding time I agree that many of these need to be changed. Updated in e291ad6296946a877c21844db772b6e33ebb0dd3
