### ISSUE TITLE
CA Review: Remove and Move Input, Output, and Calculation Variabilities

### ISSUE THREAD

**Issue by sorainsm** [peter-michalski/LatticeBoltzmannSolvers#19]
I think you can remove fluid parameters (highlighted in yellow) from your input variabilities as the actual inputs (velocity, time, etc) are listed below it.

![image](https://user-images.githubusercontent.com/11723492/66539451-e2889600-eaf5-11e9-8d99-f00f5995061f.png)

Similarly, destination for output (if it's a run-time decision) should be listed as an input instead - because someone will need to tell the system where to store the output. Encoding of output should be moved to a calculation variability if it's a compile time decision, or an input variability if its a run time decision.

![image](https://user-images.githubusercontent.com/11723492/66539517-398e6b00-eaf6-11e9-8206-51f2c5c1a658.png)

**Comment by peter-michalski** [comment]
updated in e291ad6296946a877c21844db772b6e33ebb0dd3
