### ISSUE TITLE
VnV Issue Only keep .tex and .pdf file

### ISSUE THREAD

**Issue by Zhang-Zhi-ZZ** [peter-michalski/LatticeBoltzmannSolvers#27]
Hi Peter,

I would suggest you to only keep SystVnVPlan.tex and SystVnVPlan.pdf file in SystVnVPlan folder.

**Comment by caobo1994** [comment]
And other file not named ‘SystVnV.*’
From: best-zhang-zhi
Sent: Wednesday, October 30, 2019 18:32
To: peter-michalski/LatticeBoltzmannSolvers
Cc: Subscribed
Subject: [peter-michalski/LatticeBoltzmannSolvers] VnV Issue Only keep .texand .pdf file (#27)

Hi Peter,
I would suggest you to only keep SystVnVPlan.tex and SystVnVPlan.pdf file in SystVnVPlan folder.

**Comment by smiths** [comment]
@best-zhang-zhi and @caobo1994, I believe that you are referring to the generated files being under version control.  @peter-michalski is working on that by updating his `.gitignore` file (#29).  @peter-michalski, when you correct the `.gitignore` file the generated files are not automatically removed from version control.  You will need to do that step explicitly for these files.  However, future generated files will only be added if you force them to be added.

**Comment by peter-michalski** [comment]
This is completed in 18ea7c86c3716e7421c5251e9c1be0515fa6cfb3
