### ISSUE TITLE
Review changes to CA.tex file and References.bib

### ISSUE THREAD

**Issue by smiths** [peter-michalski/LatticeBoltzmannSolvers#28]
@peter-michalski, while reviewing your CA document, I had to spend time to get it to compile.  Please review the changes that I had to make to get it to compile.  You can find the changes in ac3809a.  I also had to change the BibTeX file because my tex doesn't support unicode.  (My guess is that yours does.) 

Once you have reviewed the reasons why I had to make the changes, you can go ahead and close this issue.

**Comment by peter-michalski** [comment]
Thank you for the review. The issue is now closed as the changes were reviewed. I am now using a different tex editor.
