### ISSUE TITLE
Add a .gitignore file

### ISSUE THREAD

**Issue by smiths** [peter-michalski/LatticeBoltzmannSolvers#29]
Please add the .gitignore file to your repo. You can see a sample .gitignore file at:

https://gitlab.cas.mcmaster.ca/smiths/cas741/blob/master/BlankProjectTemplate/docs/.gitignore

When you close this issue, please include the commit number (hash) that closes the issue.

**Comment by peter-michalski** [comment]
Thank you for raising this concern. I have had the gitignore file at the root of my repo for quite some time now but I have noticed that it does not actually ignore the files that are listed. I'm still trying to figure out why this is happening.

**Comment by smiths** [comment]
The fix is simple @peter-michalski.  You just need to change the file name to `.gitignore`, not `gitignore`.  The idea of the dot is to make the file a hidden file so that it doesn't show up by default when doing a folder listing.

**Comment by peter-michalski** [comment]
This issue is closed as the file name had been changed in 18ea7c86c3716e7421c5251e9c1be0515fa6cfb3
