### ISSUE TITLE
Page iv - Abbreviations

### ISSUE THREAD

**Issue by Ao99** [peter-michalski/LatticeBoltzmannSolvers#30]
Since you put everything else in alphabetical order, it might need to be the same for "V All Input Values"

Besides, it's mentioned as "all input values" here, but almost always just "input values (V)" or "inputs (V)" in the doc. This emphasized "all" might cause some confusion.

**Comment by smiths** [comment]
@peter-michalski, I won't make this comment for all of the issues that are closed without explanation.  Whenever closing an issue, please explain why it is being closed.

**Comment by peter-michalski** [comment]
I have placed this into alphabetical order in 9f4f186b1d0d8082d1ff24448268c6859ae6de1b.

I have reopened the issues as I realized I need to make another slight change.

**Comment by peter-michalski** [comment]
Removed "all" from the abbreviations in 9e93d11b6f0e422e89ca0cf0c852089a43bae014
