### ISSUE TITLE
Page 7 - 1. input-reading-id1

### ISSUE THREAD

**Issue by Ao99** [peter-michalski/LatticeBoltzmannSolvers#31]
"An error message of “cannot read file” should be shown if the system could not read
the file."

I feel that you might need to add one more test id, with a deliberately prepared broken file, to test that the system will indeed show this message.

**Comment by peter-michalski** [comment]
This is a good suggestion. I have added another test to reflect this into 9f4f186b1d0d8082d1ff24448268c6859ae6de1b
