### ISSUE TITLE
Page 8 - 1. input-bounds-id2

### ISSUE THREAD

**Issue by Ao99** [peter-michalski/LatticeBoltzmannSolvers#32]
You might need to prepare at least two sets of test values for this test id, to test the lower bound and upper bound respectively.

For example, Re: -1000, ρ: -100

**Comment by peter-michalski** [comment]
This is a good point. I have added a lower bound test into 9f4f186b1d0d8082d1ff24448268c6859ae6de1b

**Comment by smiths** [comment]
I like that this test was added.  As I mention in my review of the VnV plan (5eaf095), the test cases could be summarized more efficiently by using a table.
