### ISSUE TITLE
Page 34 - running time

### ISSUE THREAD

**Issue by Ao99** [peter-michalski/LatticeBoltzmannSolvers#33]
"The test will be passed if both system modules are faster than the pseudo-oracle."

Instead of deciding if the test is passed or not, it might be better to just describe the percentage of time difference.

A similar situation in usability: "A final average grade of higher than 3 will indicate that the
users found the system to be user-friendly." You might not need to decide if it is user-friendly or not. A final grade might be good enough.

**Comment by smiths** [comment]
@peter-michalski, when you close an issue, please explain what was done to address the issue, or why the issue isn't relevant.  If the issue leads to changes in your document, include the commit hash where those changes were pushed.

**Comment by peter-michalski** [comment]
After reviewing the document I agree with @Ao99. I have decided it is better to describe the percentage time difference. The change is in commit 9f4f186b1d0d8082d1ff24448268c6859ae6de1b
. I have also changed the wording of the usability test to reflect the comments made in this issue.

**Comment by smiths** [comment]
Thank you @peter-michalski.  This message definitely provides better traceability to a reviewer (including me and @Ao99) to see what was done.
