### ISSUE TITLE
Page 41 - Usability Survey Questions

### ISSUE THREAD

**Issue by Ao99** [peter-michalski/LatticeBoltzmannSolvers#34]
You might need to add some explanation such as "the higher the score, the better usability it has" here.

**Comment by smiths** [comment]
@peter-michalski, please explain the reason for closing this issue.

**Comment by peter-michalski** [comment]
I agree with @Ao99 and have added his suggestion into 9f4f186b1d0d8082d1ff24448268c6859ae6de1b . This statement clarifies how the score reflects usability.

**Comment by smiths** [comment]
@peter-michalski, thank you for the link to the most relevant commit.  However, in the future, try to make your commits smaller and more focused.  That way, you can close an issue with a specific commit and future reviewers of the issue can see exactly what "code" was used to close the issue.
