### ISSUE TITLE
Test input-bounds-id2A: Testing multiple parameter at the same time.

### ISSUE THREAD

**Issue by caobo1994** [peter-michalski/LatticeBoltzmannSolvers#36]
In this test, I understand that you intend to test bounds of multiple parameters at the same time. This test might fail to detect the interaction between parameters. That is, if your make mistakes on one parameter, and this mistake is somehow masked by other parameters, you might get a false pass.

**Comment by peter-michalski** [comment]
The input bounds tests do not use the inputs to calculate a value that is later checked. In other words, each and every parameter is checked individually (there is no interaction relevant to the test) to see if it is within the acceptable range before any calculations are made. Thus it is not possible for there to be a false positive if the system is coded correctly. To reiterate, the inputs do not affect each other in these tests. Thank you for this issue, it inspired me to review the tests.
