### ISSUE TITLE
Output comparison: Compare them cell by cell?

### ISSUE THREAD

**Issue by caobo1994** [peter-michalski/LatticeBoltzmannSolvers#37]
I understand that when you try to compare the outputs that contain multiple real numbers, you try to compare them cell by cell. Does it mean that the test will get a failure result even if one floating point number is off by a little?

I also guess that you might use different algorithms for some of the mathematical operations. I wonder if the algorithm might output data with different errors. Thus, I think when you compare the cells, you might not have exact match, so you have to compare them with some tolerance in mind. However, you are comparing multiple errors, so you have to take into considerations how these errors accumulate (Adding them up, taking maximum, squared sum, etc.).

**Comment by peter-michalski** [comment]
This is a good point and ties into the advice received from @smiths . I have changed how these tests will be conducted - they will now be a comparison with the pseudo oracle and not pass/fail. The changes are in 7647cac1ce83d4133d40ed66a911a2a93bc193ce
