### ISSUE TITLE
Performance test: uncontrollable factors.

### ISSUE THREAD

**Issue by caobo1994** [peter-michalski/LatticeBoltzmannSolvers#38]
Performance test is affected by lots of aspects of environment. For example, even if you keep the hardware/OS the same, there are still something that might change. Is your computer so hot from previous computing that its CPU frequency have to be lowered? Is there any program in the background (I am sure that you cannot eliminate it) that competes with your program? Will your manual clocking introduce significant error if the time of execution is relatively small?

**Comment by peter-michalski** [comment]
I have added a note about keeping the environment reasonably static in db7867e66b260796f803f8cbbfa32adeb6c2ab8a. I have also reworded the test as the clocking will not be manual.
