### ISSUE TITLE
Message shown: Forms of message?

### ISSUE THREAD

**Issue by caobo1994** [peter-michalski/LatticeBoltzmannSolvers#39]
It seems that you assume all the messages will be shown in a window with an 'OK' button to make said window disappear. Is other forms acceptable? (Like command line messages, windows that disappear after a given time)

**Comment by peter-michalski** [comment]
Yes, other forms are acceptable. This will depend on implementation and how the system will be run by the user. I have made a clarifying comment in 1b98879961081f2e282f1c87d08d701baea347fa
