### ISSUE TITLE
Error relations: 3 iterations are enough?

### ISSUE THREAD

**Issue by caobo1994** [peter-michalski/LatticeBoltzmannSolvers#40]
I notice that you try to analyze the behavior of error in regards to the number of iterations. However, if you only take the first 3 iterations, the result will not be so accurate due to the following reasons.

1) the distance between iterations and their distance to the initial stage is too small. This means that they will be affected by lots of random factors.

2) the number of data points are 3, which is relatively small. This means that lots of patterns will have a match.

I suggest that you increase both of them. Like (5, 10, 15, 20, 25) might be good, if the error is still affected by iterations at that time.

**Comment by peter-michalski** [comment]
I have increased the number of tests to 5 and increased the distance in 4e25c91e73523c33fcd2abbbbdb756e7d1f0a9e5. More iterations will be considered in the future.
