### ISSUE TITLE
MIS multi pages - input and output format

### ISSUE THREAD

**Issue by Ao99** [peter-michalski/LatticeBoltzmannSolvers#48]
The format of input and output in the tables "Exported Access Programs" are not consistent. For example, on page 13, the input "RelaxationRate" doesn't have a type specified here, but "SpeedSound" has a type "N" here. The same situation also happens for outputs.

Would it be better to give specified types to all inputs and/or outputs? Or at least keep it consistent?

**Comment by peter-michalski** [comment]
Where appropriate this has been changed in 5943b4b93a4dd6e9cf2a1c77158ca4c9f90a3112
