### ISSUE TITLE
MIS page 24 - Exported Access Programs table

### ISSUE THREAD

**Issue by Ao99** [peter-michalski/LatticeBoltzmannSolvers#51]
In the "Exported Access Programs" table, the method "remove(InputTypes)" might need to be added.

The method "getElm()" returns an R in the table, but it returns a boolean in the later 16.4.4 description.

**Comment by peter-michalski** [comment]
Inputs do not need to be removed in the program (at least for now) so a remove function is not needed.

getElm has been clarified in cbf84efdc8249a6f6ef880860cedf4464470daac
