### ISSUE TITLE
MG issue 1

### ISSUE THREAD

**Issue by Zhang-Zhi-ZZ** [peter-michalski/LatticeBoltzmannSolvers#52]
Hi Peter,

I saw that you have input reading module and input checking module, you could combine these two as a Input Parameters Module that gets input from users and verifies the input data.

**Comment by peter-michalski** [comment]
This is a good suggestion and something I have thought about; however for the purpose of this project I will implement them as separate modules that hide separate secrets. I believe this will also make development easier for me and the primary reviewer.
