### ISSUE TITLE
MG issue 2

### ISSUE THREAD

**Issue by Zhang-Zhi-ZZ** [peter-michalski/LatticeBoltzmannSolvers#53]
Hi Peter, why is this not italic here? 
![Screen Shot 2019-11-28 at 8 48 20 PM](https://user-images.githubusercontent.com/55267358/69838191-7803f480-1220-11ea-9f50-45e4cf487fad.png)

**Comment by peter-michalski** [comment]
This is from the template of the MG document and is used for emphasis.
