### ISSUE TITLE
MIS issue 1

### ISSUE THREAD

**Issue by Zhang-Zhi-ZZ** [peter-michalski/LatticeBoltzmannSolvers#55]
Hi Peter, I saw that in section 6.4, you put the mainFunction under Local Functions, but I think it should be under Exported Access Program which is in section 6.3.2, and the mainFunction() should go to Access Routine Semantics.

**Comment by peter-michalski** [comment]
The mainFunction will not be exported to any other modules. It will be called from within the System Control Module (which is the top module), hence it is not exported and is local.
