### ISSUE TITLE
MIS Issue2

### ISSUE THREAD

**Issue by Zhang-Zhi-ZZ** [peter-michalski/LatticeBoltzmannSolvers#56]
Hi Peter, in section 7.4.3, you only have one assumption. Do you have any consumption for the  inputed file? For example, the file contains arrays.

**Comment by Zhang-Zhi-ZZ** [comment]
<img width="777" alt="Screen Shot 2019-11-28 at 9 10 28 PM" src="https://user-images.githubusercontent.com/55267358/69838925-869fdb00-1223-11ea-8259-3fc7f31f4f4f.png">
Here's an example.

**Comment by peter-michalski** [comment]
I was considering this but instead opted to add the Input Checking Module to verify that the file has the correct data and format. This way I am not assuming the structure of the file.
