### ISSUE TITLE
MIS Issue3 Spelling

### ISSUE THREAD

**Issue by Zhang-Zhi-ZZ** [peter-michalski/LatticeBoltzmannSolvers#57]
![Screen Shot 2019-11-28 at 9 12 45 PM](https://user-images.githubusercontent.com/55267358/69839014-e26a6400-1223-11ea-8b0f-c776085a52de.png)
Hi Peter, there is a spelling mistake: of not pf

**Comment by peter-michalski** [comment]
This has been updated in 8291ee1188925f576b782234acdc332a6e47ad7d
