### ISSUE TITLE
MIS Issue4

### ISSUE THREAD

**Issue by Zhang-Zhi-ZZ** [peter-michalski/LatticeBoltzmannSolvers#58]
Hi Peter, 

There are some constants like maxVariableSize in section 10.4.2, but where are you defining the value of these constants? 
![Screen Shot 2019-11-28 at 9 14 39 PM](https://user-images.githubusercontent.com/55267358/69839161-60c70600-1224-11ea-9817-5a42f745eec9.png)

**Comment by Zhang-Zhi-ZZ** [comment]
And I don't think this should be the environment variables

**Comment by peter-michalski** [comment]
This has been removed in 9264073e4537ba66f6c71c21bfee1d087a9d2e15
