### ISSUE TITLE
All pages - citation & reference style

### ISSUE THREAD

**Issue by Ao99** [peter-michalski/LatticeBoltzmannSolvers#6]
@smiths 
It seems that the citation and reference styles in this CA is not exactly the same as your template, do you think it is OK?

@peter-michalski 
If so, you might not need to make changes.

**Comment by smiths** [comment]
@Ao99, my general rule is consistency.  Unless something is imposed on us, say by a journal editor, the main thing is to be consistent.  As far as I can tell @peter-michalski is consistent with his citation style.  We don't need to make any changes here, so I'll close this issue.
