### ISSUE TITLE
Page 9 - Goal statement

### ISSUE THREAD

**Issue by Ao99** [peter-michalski/LatticeBoltzmannSolvers#7]
"G1 - Location: Predict the location of fluid particles in the lattice over time."

I might be wrong, but do you think this phrase can be more specific? Such as "the location of any fluid particle int the lattice" or "all fluid particles int the lattice"

If so, the same changes can be done to G2 and G3.

**Comment by peter-michalski** [comment]
This is a good suggestion. I have made the changes in e291ad6296946a877c21844db772b6e33ebb0dd3
