### ISSUE TITLE
Page 14 -  Input Variabilities

### ISSUE THREAD

**Issue by Ao99** [peter-michalski/LatticeBoltzmannSolvers#8]
Multiple questions here:

1. Do you think 'velocity directions' should be followed by the symbol 'k' here?

2. Since the velocities have directions, why they can be from 'Set of R'? Shouldn't they only be nonnegative real numbers?
The same question for time t: why can it be negative here?

3. I am pretty sure you accurately want <a href="https://www.codecogs.com/eqnedit.php?latex=\mathbb{R}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\mathbb{R}" title="\mathbb{R}" /></a> here. Please be careful here because R has also been defined -'Requirement'.

**Comment by sorainsm** [comment]
Piggy-backing off of @Ao99 (specifically point 3) - this is the first time the symbol for velocity is italicized (\mathbb?). This is a consistency issue that can be addressed fairly simply.

![image](https://user-images.githubusercontent.com/11723492/66538664-63925e00-eaf3-11e9-8b85-0db73bdae890.png)

**Comment by peter-michalski** [comment]
thank you, updated in e291ad6296946a877c21844db772b6e33ebb0dd3.
Note for(2): velocity directions refers to # of directions within a lattice model - these are specific to each model; however each LBM library can support multiple models
