### ISSUE TITLE
Page 18 - Pairwise Comparison of NFR

### ISSUE THREAD

**Issue by Ao99** [peter-michalski/LatticeBoltzmannSolvers#9]
1. NFR might need to be defined, explained and put in the Abbreviation Table.

2. The process of the pairwise comparison might need to be explained here. How did you get these numbers? I assume that it is one step of AHP, so you might want to explain both AHP and the process here.

**Comment by peter-michalski** [comment]
This is a good suggestion. I have made the changes in e291ad6296946a877c21844db772b6e33ebb0dd3
